In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv("/content/my_file (1).csv")
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [4]:
# Clean Column names
df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='object')

In [10]:
cleaned_columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
cleaned_columns = cleaned_columns.str.replace('year(s)', 'year')
cleaned_columns

Index(['rank', 'peak', 'all_time_peak', 'actual gross',
       'adjusted gross_(in_2022_dollars)', 'artist', 'tour_title', 'year',
       'shows', 'average_gross', 'ref.'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [19]:
# Remove spaces in columns
for i in df.select_dtypes(include='object').columns:
  df[i] = df[i].str.strip()

df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]

In [30]:
# Normalizing NA values
na_values = ['na','n/a','none',' ','null','nan']
for i in df.columns:
  if df[i].dtype == 'object':
    df[i] = df[i].replace(to_replace=na_values,value=np.nan)
df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],10[7],"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],10[7],"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,1,10[7],"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,1,10[7],"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,1,10[7],"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]

In [32]:
# Handling Missing Values
import pandas.api.types as pd_types
for col in df.columns:
  if pd_types.is_numeric_dtype(df[col]):
    df[col] = df[col].fillna(df[col].median())

  elif pd_types.is_object_dtype(df[col]):
    df[col] = df[col].fillna(df[col].mode()[0])

  else:
    df[col] = df[col].fillna(df[col].mean())

df.head(5)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],10[7],"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [34]:
# Clean currency and related symbols in columns
for col in df.columns:
  if df[col].dtype == 'object':
    df[col] = df[col].str.replace('£','')
    df[col] = df[col].str.replace('$','')
    df[col] = df[col].str.replace('€','')

df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"780,000,000","780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"13,928,571",[1]
1,2,1,7[2],"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"10,353,571",[3]
2,3,1[4],2[5],"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"4,835,294",[6]
3,4,2[7],10[7],"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"2,546,795",[7]
4,5,2[4],10[7],"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"6,522,173",[8]
5,6,2[4],10[9],"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"3,467,709",[9]
6,7,2[10],10[7],"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"2,137,405",[11]
7,7,1,10[7],"257,600,000","257,600,000",Pink,Summer Carnival †,2023–2024,41,"6,282,927",[12]
8,9,1,10[7],"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"5,226,215",[13]
9,10,1,10[7],"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"2,945,882",[14]
10,11,1,10[7],"229,100,000[b]","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"1,735,606",[15][16]
11,12,1,14[17],"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"1,118,227",[18]
12,13,1,10[7],"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"1,350,993",[19]
13,14,1[20],10[7],"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"615,385",[20]
14,15,2[c],10[7],"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"3,233,333",[5]
15,16,1,10[7],"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"1,295,775",[22]
16,17,1,10[7],"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"1,734,694",[d]
17,18,1,10[7],"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"2,070,732",[4]
18,19,1,10[7],"167,700,000[e]","204,486,106",Adele,Adele Live 2016,2016–2017,121,"1,385,950",[25]
19,20,1,10[7],"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"1,744,186",[26]

In [29]:
df.to_csv("Cleaned.csv")